entrada = str(input('Digite algo: '))
print('O tipo primitivo desse valor é ',type(entrada))
print("Só tem espaços?",entrada.isspace())
print("É um número?",entrada.isnumeric())
print("É alfabetico?",entrada.isalpha())
print('É alfanumérico',entrada.isalnum())
print("Está em minúscula",entrada.islower())
print("Está em Maiúscula",entrada.isupper())
print("Está capitalizada",entrada.istitle())